### ISSUE TITLE
Problem installing on Macosx (catalina)

### ISSUE THREAD

**Issue by SBottani** [Silmathoron/NNGT#133]
Hi Tanguy,

Doing a new installation of nngt on a fresh Catalina macosx. 
After installation of python3.8 and all the dependencies through brew I get error related to openmp when importing nngt.
Either when nngt is installed through pip, or by hand directly from the GitHub repository:

`In [1]: import nngt
clang: error: unsupported option '-fopenmp'
[WARNING @ nngt.generation.graph_connectivity]: No module named 'nngt.generation.cconnect'
	Building module nngt.generation.cconnect failed: ["distutils.errors.CompileError: command 'clang' failed with exit status 1\n"]
	Cython import failed, using non-multithreaded algorithms.
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
[WARNING @ nngt.generation.graph_connectivity]: Building module nngt.generation.cconnect failed: ["distutils.errors.CompileError: command 'clang' failed with exit status 1\n"]
	Building module nngt.generation.cconnect failed: ["distutils.errors.CompileError: command 'clang' failed with exit status 1\n"]
	Cython import failed, using non-multithreaded algorithms.

Apparently this is a common issue also with other programs on macosx. Thank you for your efforts

Best

Samuel

**Comment by SBottani** [comment]
NB
I followed hints to resolve, indicated for instance [here](https://stackoverflow.com/questions/43555410/enable-openmp-support-in-clang-in-mac-os-x-sierra-mojave) installing libomp and llvm with brew, but nothing changed.

**Comment by SBottani** [comment]
As you suggested removing multithreading by setting False in the .nngt/nngt.conf file allowed to import nngt.
Yet not very satisfactory not to have multithreading on a mac...

**Comment by Silmathoron** [comment]
Sorry for the late reply...
There seem to be issues between clang and openmp so the best way would probably be to install GCC with brew, then use ``export CC=gcc; export CXX=g++`` before the pip install

**Comment by SBottani** [comment]
Sorry, your last suggestion does not change. Mutlithreading still not possible on Macosx
