### ISSUE TITLE
Issue with distance_rule and max_proba in generation connect_nodes()

### ISSUE THREAD

**Issue by SBottani** [Silmathoron/NNGT#143]
Hi Tanguy,
There seems to be a problem since version 2.0.0 with max_proba in nngt.genertation.connect_nodes()
```
RuntimeError: Not working with max_proba and multithreading yet.
```
 for instance when
``` 
nngt.generation.connect_nodes(net, neurons, other_top, "distance_rule",
                                                   scale=mixed_scale,
                                                  max_proba=base_proba*p_other_up)
```
This in the code of simulations with top/bottom obstacles, you certainly remember (attached).

Our codes from June July always report this exception and we cannot generate the network with nngt 2.x.x versions.

I traced the distance_rule generation to `cconnect.pyx ` but couldn't see a difference in handling of max_proba between versions 1.3.x and 2.x.x, so I am at a loss here.

What's up ?  Thanks  for your help
[spatial_networks_activity.zip](https://github.com/Silmathoron/NNGT/files/5635705/spatial_networks_activity.zip)

**Comment by Silmathoron** [comment]
Hi there, as the error message suggests, I have not yet found the time to implement the ``max_proba`` feature in the multithreaded algorithms.
If you want to use it, you need to set ``nngt.set_config("multithreading", False)``.

**Comment by SBottani** [comment]
Indeed. But this occurs also with mutithreading off (forgotten to mention sorry).

**Comment by Silmathoron** [comment]
Damn, did not think that would be an issue... will fix it immediately, but if you need it now you can just add:

```python
        reload(sys.modules["nngt"].generation.connectors)
        reload(sys.modules["nngt"].generation.rewiring)
```

in ``nngt.lib.nngt_config.py``, after ``reload(sys.modules["nngt"].generation.graph_connectivity)`` (should be around line 361).

**Comment by SBottani** [comment]
thanks !

Le jeu. 3 déc. 2020 à 13:23, Tanguy Fardet <notifications@github.com> a
écrit :
