### ISSUE TITLE
issue with rng_tools

### ISSUE THREAD

**Issue by SylvainCasteilla** [Silmathoron/NNGT#150]
Hi Tanguy,
In nngt 2.2.1, a call to nngt.simulation.randomize_neural_states result in an error 
` NameError: name 'nonstring_container' is not defined`, coming from _generate_random in nngt/lib/rng_tools.py. 
The error seems to be corrected by adding, in nngt/lib/rng_tools.py,  `from nngt.lib import nonstring_container` in line 92.

**Comment by Silmathoron** [comment]
Hi there, thanks for the report!
This is indeed a bug, I'll correct it ASAP

**Comment by Silmathoron** [comment]
I guess you solved that issue on your own, but just in case, it is now fixed on master
