### ISSUE TITLE
tests call for undefined method 

### ISSUE THREAD

**Issue by g3-3k** [Silmathoron/NNGT#2]
Hi,
I think I ve provided a clean installation for clean and nest
then I tried to run tests suggested in 
http://nngt.readthedocs.io/en/latest/user/graph-generation.html
First run ok, but second crash with this log:
`Traceback (most recent call last):
  File "nngt_test.py", line 7, in <module>
    net = nngt.Network.ei_network(1000, ei_ratio=0.2)
  File "/usr/lib/python3.5/site-packages/nngt-0.5-py3.5.egg/nngt/core/graph_classes.py", line 922, in ei_network
    pop = NeuralPop.ei_population(size, ei_ratio, None, en_model, en_param,
AttributeError: type object 'NeuralPop' has no attribute 'ei_population'1`

and reading the code actually there is no other reference to `ei_population`

**Comment by Silmathoron** [comment]
Yep, the documentation was not up to date anymore, this should be fixed.

**Comment by Silmathoron** [comment]
Ficed by [8477a47](https://github.com/Silmathoron/NNGT/commit/8477a47d46726ec43c8449b1e7c7bdea5c8fdab7)
